# Python CircleCI 2.1 configuration file
version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
  
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: setup conda
      - run:
          name: setup conda
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
            chmod +x ~/miniconda.sh && ~/miniconda.sh -b;
            echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV;
      # Step 3: install packages in conda env
      - run:
          name: Install packages in conda environment
          command: |
            conda init bash
            source ~/.bashrc
            echo "conda version = $(conda --version)"
            conda create -n quailenv
            conda install -n quailenv python=3.9.7 numpy scipy pytest matplotlib pytest-cov
            source activate quailenv
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            conda init bash
            source ~/.bashrc
            source activate quailenv
            cd test
            pytest --cov=../src --cov-report=xml
            cd end_to_end
            python generate_tests.py
            cd ..
            pytest -v
      - codecov/upload
